# -*- coding: utf-8 -*-
"""TCC_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QoMixl46EyFNKIUSSvrDE32f2xCTAaz7
"""

#Bruna Puggina Lima - ECP - Trechos de código - TG2

#Código Resumo : Considerando todas as consultas, porém apenas para o mês de março

#Coletando informações (Display) de quantas linhas tem no total da tabela original (tcp) e quantas tem a coluna lastip6 como NaN

# Coletando informações de quantas linhas tem no total da tabela original e quantas tem a coluna lastip6 como NaN 
import pandas as pd
pd.set_option('display.max_rows', 4) 

mar_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_03_2019_TCP.csv', usecols=['lastip6'])
martcpv6 = mar_tcp.query('lastip6.notnull()', engine='python')
display(mar_tcp)
display(martcpv6)

#Coletando informações (Display) de quantas linhas tem no total da tabela original (UDP) e quantas tem a coluna lastip6 como NaN

import pandas as pd
pd.set_option('display.max_rows', 4) 

mar_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_03_2019_UDP.csv', usecols=['lastip6'])
marudpv6 = mar_udp.query('lastip6.notnull()', engine='python')
display(mar_udp)
display(marudpv6)

#Coletando informações (Display) de quantas vezes cada item de uma coluna específica aparece no arquivo da tabela original (TCP) e da tabela formada pelas linhas da tabela original nas quais a coluna lastip6 é nula.

import pandas as pd
pd.set_option('display.max_rows', None) 

mar_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_03_2019_TCP.csv', usecols=['lastip6', 'conn_tech','osversion','brand', 'end_tech'])
nmartcp6 = mar_tcp.query('lastip6.isnull()', engine='python')

mar_tcp.groupby(by='osversion').size()

nmartcp6.groupby(by='osversion').size()

mar_tcp.groupby(by='conn_tech').size()

nmartcp6.groupby(by='conn_tech').size()

mar_tcp.groupby(by='brand').size()

nmartcp6.groupby(by='brand').size()

#Coletando informações (Display) de quantas vezes cada item de uma coluna específica aparece no arquivo da tabela original (UDP) e da tabela formada pelas linhas da tabela original nas quais a coluna lastip6 é nula.

import pandas as pd
pd.set_option('display.max_rows', None) 

mar_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_03_2019_UDP.csv', usecols=['lastip6', 'conn_tech','osversion','brand', 'end_tech'])
nmarudpv6 = mar_udp.query('lastip6.isnull()', engine='python')

mar_udp.groupby(by='osversion').size()

nmarudpv6.groupby(by='osversion').size()

mar_udp.groupby(by='conn_tech').size()

nmarudpv6.groupby(by='conn_tech').size()

#Observação: Aqui filtra por uma marcas específica para ver quantas vezes ela aparece na tabela

#mar_udp.groupby(by='brand').size()

len(mar_udp[mar_udp['brand'] == 'Multilaser'])

len(nmarudpv6[nmarudpv6['brand'] == 'Multilaser'])