#Bruna Puggina Lima - ECP - Trechos de código - TG

# Coletando informações (Display) de quantas linhas tem no total da tabela original (TCP) e quantas tem a coluna lastip6 como NaN 

import pandas as pd
pd.set_option('display.max_rows', 4) 

mar_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_03_2019_TCP.csv', usecols=['lastip6'])
abr_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_04_2019_TCP.csv', usecols=['lastip6'])
mai_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_05_2019_TCP.csv', usecols=['lastip6'])
jun_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_06_2019_TCP.csv', usecols=['lastip6'])
jul_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_07_2019_TCP.csv', usecols=['lastip6'])
ago_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_08_2019_TCP.csv', usecols=['lastip6'])
set_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_09_2019_TCP.csv', usecols=['lastip6'])
out_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_10_2019_TCP.csv', usecols=['lastip6'])
nov_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_11_2019_TCP.csv', usecols=['lastip6'])
dez_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_12_2019_TCP.csv', quoting = 3, usecols=['lastip6'])
jan_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_01_2020_TCP.csv', usecols=['lastip6'])
fev_tcp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_02_2020_TCP.csv', usecols=['lastip6'])

martcpv6 = mar_tcp.query('lastip6.notnull()', engine='python')
abrtcpv6 = abr_tcp.query('lastip6.notnull()', engine='python')
maitcpv6 = tcp_tcp.query('lastip6.notnull()', engine='python')
juntcpv6 = jun_tcp.query('lastip6.notnull()', engine='python')
jultcpv6 = jul_tcp.query('lastip6.notnull()', engine='python')
agotcpv6 = ago_tcp.query('lastip6.notnull()', engine='python')
settcpv6 = set_tcp.query('lastip6.notnull()', engine='python')
outtcpv6 = out_tcp.query('lastip6.notnull()', engine='python')
novtcpv6 = nov_tcp.query('lastip6.notnull()', engine='python')
deztcpv6 = dez_tcp.query('lastip6.notnull()', engine='python')
jantcpv6 = jan_tcp.query('lastip6.notnull()', engine='python')
fevtcpv6 = fev_tcp.query('lastip6.notnull()', engine='python')

display(mar_tcp)
display(martcpv6)
display(abr_tcp)
display(abrtcpv6)
display(mai_tcp)
display(maitcpv6)
display(jun_tcp)
display(juntcpv6)
display(jul_tcp)
display(jultcpv6)
display(ago_tcp)
display(agotcpv6)
display(set_tcp)
display(settcpv6)
display(out_tcp)
display(outtcpv6)
display(nov_tcp)
display(novtcpv6)
display(dez_tcp)
display(deztcpv6)
display(jan_tcp)
display(jantcpv6)
display(fev_tcp)
display(fevtcpv6)