#Bruna Puggina Lima - ECP - Trechos de código - TG

# Coletando informações (Display) de quantas linhas tem no total da tabela original (UDP) e quantas tem a coluna lastip6 como NaN 

import pandas as pd
pd.set_option('display.max_rows', 4) 

mar_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_03_2019_UDP.csv', usecols=['lastip6'])
abr_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_04_2019_UDP.csv', usecols=['lastip6'])
mai_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_05_2019_UDP.csv', usecols=['lastip6'])
jun_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_06_2019_UDP.csv', usecols=['lastip6'])
jul_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_07_2019_UDP.csv', usecols=['lastip6'])
ago_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_08_2019_UDP.csv', usecols=['lastip6'])
set_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_09_2019_UDP.csv', usecols=['lastip6'])
out_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_10_2019_UDP.csv', usecols=['lastip6'])
nov_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_11_2019_UDP.csv', usecols=['lastip6'])
dez_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_12_2019_UDP.csv', usecols=['lastip6'])
jan_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_01_2020_UDP.csv', usecols=['lastip6'])
fev_udp = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Netmetric_02_2020_UDP.csv', usecols=['lastip6'])

marudpv6 = mar_udp.query('lastip6.notnull()', engine='python')
abrudpv6 = abr_udp.query('lastip6.notnull()', engine='python')
maiudpv6 = udp_udp.query('lastip6.notnull()', engine='python')
junudpv6 = jun_udp.query('lastip6.notnull()', engine='python')
juludpv6 = jul_udp.query('lastip6.notnull()', engine='python')
agoudpv6 = ago_udp.query('lastip6.notnull()', engine='python')
setudpv6 = set_udp.query('lastip6.notnull()', engine='python')
outudpv6 = out_udp.query('lastip6.notnull()', engine='python')
novudpv6 = nov_udp.query('lastip6.notnull()', engine='python')
dezudpv6 = dez_udp.query('lastip6.notnull()', engine='python')
janudpv6 = jan_udp.query('lastip6.notnull()', engine='python')
fevudpv6 = fev_udp.query('lastip6.notnull()', engine='python')

display(mar_udp)
display(marudpv6)
display(abr_udp)
display(abrudpv6)
display(mai_udp)
display(maiudpv6)
display(jun_udp)
display(junudpv6)
display(jul_udp)
display(juludpv6)
display(ago_udp)
display(agoudpv6)
display(set_udp)
display(setudpv6)
display(out_udp)
display(outudpv6)
display(nov_udp)
display(novudpv6)
display(dez_udp)
display(dezudpv6)
display(jan_udp)
display(janudpv6)
display(fev_udp)
display(fevudpv6)